### ISSUE TITLE
Implementation plan

### ISSUE THREAD

**Issue by paulpopus** [NouanceLabs/payload-dashboard-analytics#2]
## Part 1 - backend API

- [ ] Add reusable provider function/class that allows us to authenticate and fetch data:
  - [ ] per last 30 days for whole site
  - [ ] last 7 days for whole site
  - [ ] per last 30 days per content item
  - [ ] per last 7 days per content item
- [ ] Backend API routes with authentication 
- [ ] Update plugin config to account for these
- [ ] Add a matcher function for collections (eg. how do we map analytics URL data to collections in Payload? should be an end developer configuration item)
- [ ] Support Plausible and Google Analytics

## Part 2 - frontend components

- [ ] Charts made using https://react-charts.tanstack.com/ ?
- [ ] Add dashboard statistics component configurable:
  - [ ] Before dashboard
  - [ ] After dashboard
- [ ] Add per content item analytics data

## Part 3 - allow further extension

- [ ] Expose the reusable provider for end developer to create their own integration if needed
- [ ] Support matomo
- [ ] Support umami
